### ISSUE TITLE
Migration to .NET 6.0

### ISSUE THREAD

**Issue by BleuBleu** [flathub/org.famistudio.FamiStudio#11]
Hi @ernstp!

In a couple week, ill release FamiStudio 4.1.0. This version will ditch mono, in favor of the more modern .NET 6.0. 

I was wondering if you had half and hour on your hands to help with that. Otherwise ill probably have to spend a full weekend understanding how things work.

- I see there is a package we can use for that. The example given is in JSON, not sure how that translates in YAML?
https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6

- Launching the app will be `dotnet FamiStudio.dll` instead of `mono FamiStudio.exe`

- _(Optional)_ Another thing we can do, is drop the symlink to openal (`ln -sf /usr/lib/x86_64-linux-gnu/libopenal.so.1 /app/bin/libopenal32.so`), since with .NET, we will first try to load the openAL on the person's machine, then fallback on our version if that fails.
https://github.com/BleuBleu/FamiStudio/blob/6cc324fb606e193f8bca0962b11bad4ee8ef99ca/FamiStudio/Source/Platform/Linux/Platform.cs#L53

Let me know if you have time, I can send you a beta build, or you can try to do it blindly. Otherwise ill give it a try and annoy you with billions of question!

-Mat

**Comment by ernstp** [comment]
If you work with pull requests there will automatically be test-builds that can be downloaded.

So you need to change this to the dotnet6:
```
sdk-extensions:
  - org.freedesktop.Sdk.Extension.mono6
```

And run the appropriate install.sh.

Launching is done in the famistudio.sh script.

**Comment by ernstp** [comment]
Looks like it works for me

**Comment by BleuBleu** [comment]
Cool, thanks for the test!
