### ISSUE TITLE
Opinion on OpenAL issue

### ISSUE THREAD

**Issue by BleuBleu** [flathub/org.famistudio.FamiStudio#2]
Hi @ernstp just opening this to get your opinion on something.

Right now I distribute a pre-compiled OpenAL with FamiStudio. We discovered that on some rare machines, audio just doesn't work with that one. You can read the thread:

https://github.com/BleuBleu/FamiStudio/issues/79

If I read the script flatpak script correctly, we actually dont use that one, instead, we create a symlink to real OpenAL that the person has. This doesn't seem to always work for some reason. Might be a limitation in Mono or something? Any ideas are welcome here?

What *does* seem to work (at least for the person in the issue), is to use a simple [DLL map](https://www.mono-project.com/docs/advanced/pinvoke/dllmap/). Basically a small file that tells Mono "if you want to load this DLL, then load this lib instead.

I wrote a small procedure here and youll find the dll map that seem to work. I was wondering if we could try that instead of the symlink approach? 

https://famistudio.org/doc/troubleshooting/#audio-issues-on-linux

-Mat

**Comment by ernstp** [comment]
In the Flatpak we replace it with OpenAL from inside the Flatpak runtime.
This was to get a newer OpenAL compiled with more supported features etc...
In general I don't see any reason why you should distribute an OpenAL lib at all.

**Comment by BleuBleu** [comment]
No that's not what im saying at all!

Im saying the symlink solution does not seem to work for some people (at least one). Can you think of why?

Could we switch to a DLLMap, which will accomplish the same thing (tell Mono to load the openal the the person has on their system) instead?

-Mat

**Comment by ernstp** [comment]
> Im saying the symlink solution does not seem to work for some people (at least one). Can you think of why?

A Pipewire bug? It's brand new after all.

> EDIT: That person does not have "/usr/lib/x86_64-linux-gnu/libopenal.so.1". Seems like on some system its installed in a different path, could that be the issue?

The Flatpak has OpenAl bundled so it doesn't matter.

**Comment by BleuBleu** [comment]
How do you explain that the flatpak build didn't work for him. Then when he switched to simply downloading the standalone build and pointing it to its own OpenAL it started working.

Sounds to me like there is something wrong with the environment we provide in the flatpak build no?

-Mat

**Comment by axredneck** [comment]
I'm that person who has a problem. I'm on Arch Linux. I have `$HOME/.local/share/flatpak/app/org.famistudio.FamiStudio/current/active/files/bin/libopenal32.so` that points to non-existent `/usr/lib/x86_64-linux-gnu/libopenal.so.1`

**Comment by ernstp** [comment]
Flatpaks run in their own environment (that's the point of flatpaks) so that's not how it works.
You have to do
`flatpak run  --command=sh org.famistudio.FamiStudio`
and then you can check with
`ls -l /app/bin/`

However, the flatpak runtime has libOpenAL 1.20.1 while Arch now has 1.21.1. Perhaps there's something there that works better with Pipewire that Flatpak should bring in to their runtime...

**Comment by ernstp** [comment]
@axredneck  I think you should report your issue here and see what they say... https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues

**Comment by BleuBleu** [comment]
@ernstp That's actually an interesting theory. 

One way of quickly testing this without annoying the freedesktop people would be for me to compile a version of 1.21.1 locally and send that to @axredneck for a quick test. FamiStudio also shipped with 1.20.1, same as flatpak, and has the same exact behavior. I read the change log and didnt see anything specific for pipewire, but it does seem to fix a ton of stuff.

Ill try to find time to do this this week and report back.

-Mat

**Comment by ernstp** [comment]
Right, sounds good. Though I think they don't mind bug reports to help get things working!

(I'm not sure exactly how to locally modify a Flatpak runtime unfortunately... )

**Comment by BleuBleu** [comment]
Actually i just had some time while my code was compiling. 

@axredneck lets do an experiment:

1) Download the stock Linux FamiStudio from https://famistudio.org/
2) Replace the libopenal32.so that is included (1.20.1) with this one (1.21.1). If you ever get confused, the smaller one is the newest one.
3) If that fixes the problem, then this mean all we need is a version upgrade and well annoy the freedesktop people!
4) If that DOESNT work, well need to think some more! :)

-Mat

[libopenal32 (1.21.1).zip](https://github.com/flathub/org.famistudio.FamiStudio/files/6692433/libopenal32.1.21.1.zip)

**Comment by axredneck** [comment]
No, FamiStudio freezes with this OpenAL build too.

**Comment by BleuBleu** [comment]
Damn... Again thanks for the debugging. @axredneck 

Do we know which version you are running on arch at the moment (the one installed on your system).

This is what we know so far:
* FamiStudio + OpenAL 1.20.1 doesnt work
* FamiStudio + OpenAL 1.21.1 doesnt work
* FamiStudio + Flatpak (with has OpenAL 1.20.1) doesnt work

-Mat

**Comment by axredneck** [comment]
> Do we know which version you are running on arch at the moment (the one installed on your system).

1.21.1

**Comment by BleuBleu** [comment]
Sorry for the delay.

Ok, when you are using your version of the lib and everything works. Does FamiStudio still say that is uses the default ALSA output or does it use a different one. To check that, start FamiStudio manually in a terminal (mono FamiStudio.exe) and see what it prints. This was added in 3.0.1, so make sure you have that.

Should look like this:
`Default OpenAL audio device is 'ALSA Default'`

Im asking this because the version I compile only has alsa support i think, but the version that comes with arch seem to be compiled with a lot more back ends. (alsa, fluidsynth, jack, pulse, portaudio, etc.).

-Mat

**Comment by axredneck** [comment]
It says `Default OpenAL audio device is 'GP107GL High Definition Audio Controller Цифровой стерео (HDMI)'`

**Comment by BleuBleu** [comment]
That's really interesting actually. Its not using the same "default device" as the OpenAL I compile. This device seems to be your nvidia HDMI audio output? Is that how your audio is setup on your computer?

-Mat

**Comment by axredneck** [comment]
Yes, it's my Nvidia HDMI, and it's the only output device currently enabled on my setup.

**Comment by BleuBleu** [comment]
Ok, if you don't mind helping more, ill send you a custom build where we can choose the output to use. Well try all of them one by one and see if there is one that works! :) Seems like that "alsa default" is maybe not good on your computer.

-Mat

**Comment by axredneck** [comment]
> ill send you a custom build where we can choose the output to use

Did you prepare that build?

**Comment by axredneck** [comment]
I just uninstalled `pulseaudio-alsa` package and looks like now everything works.
