### ISSUE TITLE
Why is the build failing?

### ISSUE THREAD

**Issue by BleuBleu** [flathub/org.famistudio.FamiStudio#3]
Hi @ernstp !

I was wondering if you knew why the build is failing now? I added ffmpeg as an extension and the build machines seems to run out of disk space? Do you happen to know what could be causing this?

-Mat

**Comment by ernstp** [comment]
I don't think it's related to anything you did: https://github.com/flathub/flathub/issues/2450

**Comment by BleuBleu** [comment]
Oh lol, thanks! haha
