### ISSUE TITLE
Why is the build failing?

### ISSUE THREAD

**Issue by BleuBleu** [flathub/org.famistudio.FamiStudio#4]
@ernstp Got any idea? I just pushed a new version as usual.

```
error: org.freedesktop.Sdk.Extension.mono6/x86_64/20.08 not installed
```

-Mat

**Comment by ernstp** [comment]
Typo in the URL, 
https://flathub.org/builds/#/builders/35/builds/10810
Failed to download sources: module app: The requested URL returned error: 404
3.3.0/FamiStudio323-LinuxAMD64.zip
should be
3.3.0/FamiStudio330-LinuxAMD64.zip

**Comment by ernstp** [comment]
If you do your uploads as pull requests you get a nice test run by the flathub bots btw!

**Comment by BleuBleu** [comment]
Oh you gotta be kidding me! 

Im an idiot. 

Sorry about that, will fix immediately.

-Mat
