### ISSUE TITLE
End of life warning?

### ISSUE THREAD

**Issue by BleuBleu** [flathub/org.famistudio.FamiStudio#5]
Ive got reports from users getting this. Do you know what that mean? @ernstp 

I got this message when I installed:

```
Info: org.freedesktop.Platform.VAAPI.Intel//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
```

And now every time I run flatpak update I get the messages:

```
Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.famistudio.FamiStudio

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.famistudio.FamiStudio
```

**Comment by BleuBleu** [comment]
Also its worth nothing that FamiStudio 4.0 doesn't use GTK#, GTK or anything Gnome related anymore. 
So I'm not sure how that impacts the runtime we use. I don't know how any of this works.

-Mat

**Comment by ernstp** [comment]
It's a suggestion to update https://github.com/flathub/org.famistudio.FamiStudio/blob/master/org.famistudio.FamiStudio.yml#L3 to a later runtime.

Interesting, what will 4.0 use instead?

**Comment by BleuBleu** [comment]
Hi. Thanks for the reply.

What's newer than 3.38? I tried googling a bunch and I still don't understand where I'm supposed to find these runtime versions. Everything is very poorly documented, or im looking at the wrong places. 

4.0.0 is already out, it just uses GLFW and custom draw widget. I don't know if it means we could change the runtime we use? Since we dont need gnome anymore? Again, i have no clue which one to use, which version. 

-Mat

**Comment by ernstp** [comment]
Here's some info:
https://docs.flatpak.org/en/latest/available-runtimes.html
Found this:
https://gitlab.gnome.org/GNOME/gnome-build-meta/-/wikis/home
So looks like gnome-41 is the latest.
But yeah you could probably drop down to the plain Freedesktop runtime then. I can have a look at it...

**Comment by BleuBleu** [comment]
Thanks!
